/* Copyright (c) Microsoft Corporation.
   Licensed under the MIT License. */

#ifndef _AZURE_CONFIG_H
#define _AZURE_CONFIG_H

typedef enum
{
    None         = 0,
    WEP          = 1,
    WPA_PSK_TKIP = 2,
    WPA2_PSK_AES = 3
} WiFi_Mode;

// ----------------------------------------------------------------------------
// WiFi connection config
// ----------------------------------------------------------------------------
#define WIFI_SSID     "NETGEAR88"
#define WIFI_PASSWORD "strongriver683"
#define WIFI_MODE     WPA2_PSK_AES

// ----------------------------------------------------------------------------
// Azure IoT Dynamic Provisioning Service
//    Define this to use the DPS service, otherwise direct IoT Hub
// ----------------------------------------------------------------------------
#define ENABLE_DPS

// ----------------------------------------------------------------------------
// Azure IoT DPS connection config
//    IOT_DPS_ID_SCOPE:        The DPS ID Scope
//    IOT_DPS_REGISTRATION_ID: The DPS device Registration Id
// ----------------------------------------------------------------------------
// 2022 02 19 MEV: this DP ID Scope represents MEV's IOTC Application (no  IP or URL required)...
#define IOT_DPS_ID_SCOPE        "0ne004C4ED6"
#define IOT_DPS_REGISTRATION_ID "MXChip-MV-03"

// ----------------------------------------------------------------------------
// Azure IoT Hub connection config
//    IOT_HUB_HOSTNAME:  The Azure IoT Hub hostname
//    IOT_HUB_DEVICE_ID: The Azure IoT Hub device id
// ----------------------------------------------------------------------------
#define IOT_HUB_HOSTNAME  ""
#define IOT_HUB_DEVICE_ID ""

// ----------------------------------------------------------------------------
// Azure IoT DPS Self-Signed X509Certificate
//    Define this to connect to DPS or Iot Hub using a X509 certificate
// ----------------------------------------------------------------------------
//#define ENABLE_X509

// ----------------------------------------------------------------------------
// Azure IoT device SAS key
//    The SAS Primary key generated by Azure IoT
// ----------------------------------------------------------------------------
// 2022 02 18 MEV: this is the SAS key for MXChip "MX-MV-01"...
// #define IOT_DEVICE_SAS_KEY "FyKsTPpdUbJAerQhrueYLUf3xE+F+Yx9wEQChJhO0hw="
// 2022 02 18 MEV: this is the SAS key for MXChip "MX-MV-02"...
//#define IOT_DEVICE_SAS_KEY "crmw6idF5G4i28nnffdkMpaOKgNfX1XuQfIDUHDtzZU="
// 2022 04 13 MEV: this is the SAS key for MXChip "MX-MV-03"...
#define IOT_DEVICE_SAS_KEY "6utON+DgJiA3jEFZAS4nu6TVbO0Cx5wxzxV8JrFKg6U="

#endif // _AZURE_CONFIG_H
